### ISSUE TITLE
Plugin Installed but buttons not working in the floorplan tab

### ISSUE THREAD

**Issue by MusicMano** [netbox-community/netbox-floorplan-plugin#27]
The plugin is installed and the floorplan tab shows up under locations and sites. But none of the buttons work. Would anyone here know what the fix would be? I am using netbox version 3.7.5 and whatever the latest version of the floorplan plugin is

**Comment by Lucas729** [comment]
Same for me. I have last vetsion of Netbox 4.0.3.

**Comment by NotHBlocks** [comment]
I´ve installeed it today and had the same issue. Netbox version 4.0.3 Python version 3.11

**Comment by benraven** [comment]
Just had the same issue, and hit F12 to see what was happening. I was getting 404s on some static files which meant that the buttons that referred to those files didn't work:
- ${NETBOX_URL}/static/netbox_floorplan/floorplan/edit.js
- ${NETBOX_URL}/static/netbox_floorplan/vendors/fabric.js
- ${NETBOX_URL}/static/netbox_floorplan/vendors/jq.js

I took a look at the static folder on the server, and noticed that the files for this plugin were missing, which I fixed by running:
- `sudo ./venv/bin/python3 netbox/manage.py collectstatic`

**Comment by Lucas729** [comment]
It works! Thanks. I think you need to be in venv environment

`source /opt/netbox/venv/bin/activate`

and then run

`python manage.py collectstatic`

and this works for me.

**Comment by NotHBlocks** [comment]
> Just had the same issue, and hit F12 to see what was happening. I was getting 404s on some static files which meant that the buttons that referred to those files didn't work:
> 
> * ${NETBOX_URL}/static/netbox_floorplan/floorplan/edit.js
> * ${NETBOX_URL}/static/netbox_floorplan/vendors/fabric.js
> * ${NETBOX_URL}/static/netbox_floorplan/vendors/jq.js
> 
> I took a look at the static folder on the server, and noticed that the files for this plugin were missing, which I fixed by running:
> 
> * `sudo ./venv/bin/python3 netbox/manage.py collectstatic`

Thank you. That helped. But the button "Add Label" do not work. If I click it. nothing happens. All the other buttons work.

**Comment by MusicMano** [comment]
I have done what I could to this plugin to work. Seems like my permissions have gotten messed up. I am not able to successfully run the collectstatic cmd.


(venv) david@Netbox:/opt/netbox/netbox$ python manage.py collectstatic

You have requested to collect static files at the destination
location as specified in your settings:

    /opt/netbox/netbox/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 135, in collect
    handler(path, prefixed_path, storage)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 378, in copy_file
    self.storage.save(prefixed_path, source_file)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/files/storage/base.py", line 38, in save
    name = self._save(name, content)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/files/storage/filesystem.py", line 87, in _save
    os.makedirs(directory, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/netbox/netbox/static/netbox_floorplan'

Any thought on how to regain permissions would be appreciated

**Comment by MusicMano** [comment]
Sudo -s 
Got me where I needed to be to run the commands
