### ISSUE TITLE
ImproperlyConfigured: Application labels aren't unique, duplicates: netbox_topology_views

### ISSUE THREAD

**Issue by lukassavukaitis** [netbox-community/netbox-floorplan-plugin#47]
I'm getting this error when running migrations after installing this plugin:

```
Traceback (most recent call last):
  File "/opt/netbox/netbox/netbox/../manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/apps/registry.py", line 93, in populate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: netbox_topology_views
```

**Comment by cruse1977** [comment]
Unable to replicate this - there is no reference at all to netbox_topology_views within floorplan.

You would need to provide exact steps to reproduce from a fresh install.
