### ISSUE TITLE
Error installing floorplan_plugin

### ISSUE THREAD

**Issue by gignat88** [netbox-community/netbox-floorplan-plugin#48]
Hello,

I have followed guides from https://netboxlabs.com/docs/netbox/en/stable/installation/ and managed to install it. Now i want do install the plugin and i got this error :

:~$ sudo pip install netbox-floorplan-plugin
[sudo] password for netbox:
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

i have activated the virtual environment and got this error : 

$ pip install netbox-floorplan-plugin
Collecting netbox-floorplan-plugin
  Downloading netbox_floorplan_plugin-0.4.0-py3-none-any.whl.metadata (2.1 kB)
Downloading netbox_floorplan_plugin-0.4.0-py3-none-any.whl (278 kB)
Installing collected packages: netbox-floorplan-plugin
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/opt/netbox/venv/lib/python3.12/site-packages/netbox_floorplan'
Check the permissions.

run it with sudo : 

:~$ sudo pip install netbox-floorplan-plugin
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

And here i got blocked. Can anyone help me with a complete guide to install this plugin ? 

i have installed NetBox v4.1.3

**Comment by maciejopalinski** [comment]
You forgot this part of the install guide: https://netboxlabs.com/docs/netbox/en/stable/installation/3-netbox/#__code_22
```
source /opt/netbox/venv/bin/activate
```
Netbox python package installation always takes place in the python virtual environment. Don't forget to activate it.

**Comment by maciejopalinski** [comment]
Also, this plugin will not work with Netbox v4.1.3 as of today. It still waits to be updated to the newest Netbox version in this PR: #49

**Comment by gignat88** [comment]
even if netbox v 4.1.3 does not support , it could install the  plugin and this one will not work or it will not install at all ?

because i have tried to install it and i got the same error over and over ( i've also asked chatgpt and no result )

steps i've followed :

- i've created file local.requirements.txt

(venv) netbox@netbox-J42-Nano:/opt/netbox$ cat local.requirements.txt
netbox-floorplan-plugin

- i've installed netbox-floorplan-plugin : 

(venv) netbox@netbox-J42-Nano:/opt/netbox$ sudo /opt/netbox/venv/bin/pip install netbox-floorplan-plugin
Collecting netbox-floorplan-plugin
  Using cached netbox_floorplan_plugin-0.4.0-py3-none-any.whl.metadata (2.1 kB)
Using cached netbox_floorplan_plugin-0.4.0-py3-none-any.whl (278 kB)
Installing collected packages: netbox-floorplan-plugin
Successfully installed netbox-floorplan-plugin-0.4.0

(venv) netbox@netbox-J42-Nano:/opt/netbox$ /opt/netbox/venv/bin/pip show netbox-floorplan-plugin
Name: netbox-floorplan-plugin
Version: 0.4.0
Summary: Netbox Plugin to support graphical floorplans
Home-page: https://github.com/netbox-community/netbox-floorplan-plugin.git
Author: Tony Nealon
Author-email: tony@worksystems.co.nz
License: LGPLv3+
Location: /opt/netbox/venv/lib/python3.12/site-packages
Requires:
Required-by:

(venv) netbox@netbox-J42-Nano:/opt/netbox$ /opt/netbox/venv/bin/pip list | grep netbox-floorplan-plugin
netbox-floorplan-plugin       0.4.0

-i've added in configuration.py : 

# Enable installed plugins. Add the name of each plugin to the list.
PLUGINS = [
    'netbox_floorplan_plugin',
]

# Plugins configuration settings. These settings are used by various plugins that the user may have installed.
# Each key in the dictionary is the name of an installed plugin and its value is a dictionary of settings.
# PLUGINS_CONFIG = {
#     'my_plugin': {
#         'foo': 'bar',
#         'buzz': 'bazz'
#     }
# }

# Remote authentication support

this is the error i receive after ./upgrade.sh script running L


**Skipping local dependencies (local_requirements.txt not found)**
Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "/opt/netbox/netbox/netbox/settings.py", line 801, in <module>
    plugin = importlib.import_module(plugin_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'netbox_floorplan_plugin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 104, in wrapper
    saved_locale = translation.get_language()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/utils/translation/__init__.py", line 211, in get_language
    return _trans.get_language()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/utils/translation/__init__.py", line 66, in __getattr__
    if settings.USE_I18N:
       ^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/conf/__init__.py", line 89, in __getattr__
    self._setup(name)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/conf/__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 804, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Unable to import plugin netbox_floorplan_plugin: Module not found. Check that the plugin module has been installed within the correct Python environment.
(venv) netbox@netbox-J42-Nano:/opt/netbox$ /opt/netbox/venv/bin/pip show netbox-floorplan-plugin

it said that local_requiremets.txt not found

i don't know what to do anymore; although it seems to be very easy to install it it is very complicated

**Comment by maciejopalinski** [comment]
Netbox v4.1.3 will not start with this plugin installed, but the plugin can be installed.
There are a couple of mistakes that you are making:
1. File name is `local_requirements.txt` (**not** `local.requirements.txt`).
2. Package name is `netbox-floorplan-plugin`, but in `configuration.py` you should put: `PLUGINS = ['netbox_floorplan']` as per [the plugin install docs](https://github.com/netbox-community/netbox-floorplan-plugin/tree/master?tab=readme-ov-file#installing).

Let me know if that fixed your issues.

**Comment by gignat88** [comment]
hello,

1.so i've installed netbox v4.0.11 because plugin netbox_floorplan is compatible with this version

2. i've created local_requirements.txt and added line "netbox_floorplan" :
*@* :/opt/netbox/netbox/netbox$ cat local_requirements.txt
netbox-floorplan-plugin

3.i've edited configuration.py and added in plugins field the following : 

# Enable installed plugins. Add the name of each plugin to the list.
PLUGINS = ['netbox_floorplan']

4. i've tried to run sudo ./venv/bin/python3 netbox/manage.py makemigrations netbox_floorplan_plugin and got error : 
Traceback (most recent call last):
  File "/opt/netbox/netbox/netbox/settings.py", line 779, in <module>
    plugin = importlib.import_module(plugin_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'netbox_floorplan'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 454, in execute
    self.check()
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/checks/caches.py", line 64, in check_file_based_cache_is_absolute
    for alias, config in settings.CACHES.items():
                         ^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/conf/__init__.py", line 89, in __getattr__
    self._setup(name)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/conf/__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 782, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Unable to import plugin netbox_floorplan: Module not found. Check that the plugin module has been installed within the correct Python environment.

from what i see the error is No module named 'netbox_floorplan' so there is a mistype somewere


5. the same error i've got even when i run upgrade.sh , bellow are the last lines from running upgrade.sh : 

Skipping local dependencies (local_requirements.txt not found)
Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "/opt/netbox/netbox/netbox/settings.py", line 779, in <module>
    plugin = importlib.import_module(plugin_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'netbox_floorplan'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 104, in wrapper
    saved_locale = translation.get_language()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/utils/translation/__init__.py", line 211, in get_language
    return _trans.get_language()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/utils/translation/__init__.py", line 66, in __getattr__
    if settings.USE_I18N:
       ^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/conf/__init__.py", line 89, in __getattr__
    self._setup(name)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/conf/__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 782, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Unable to import plugin netbox_floorplan: Module not found. Check that the plugin module has been installed within the correct Python environment.

i see that there is also an error that (local_requirements.txt not found) ; i've copied local_requirements.txt from /op/netbox/netbox/netbox/local_requirements.txt to /op/netbox/ and run upgrade and seems that it's ok now  : 

Running migrations:
  Applying netbox_floorplan.0001_initial... OK
  Applying netbox_floorplan.0002_floorplan_measurement_unit_alter_floorplan_scale... OK
  Applying netbox_floorplan.0003_floorplan_canvas... OK
  Applying netbox_floorplan.0004_alter_floorplan_options... OK
  Applying netbox_floorplan.0005_alter_floorplan_site... OK
  Applying netbox_floorplan.0006_delete_floorplanobject... OK
  Applying netbox_floorplan.0007_alter_floorplan_options_and_more... OK
Checking for missing cable paths (python3 netbox/manage.py trace_paths --no-i


- opened netbox and plugin is installed, but there is no button to add something : 
![image](https://github.com/user-attachments/assets/7897c530-62e3-4b73-82d0-f3163d371ee8)

some help please ? thx a lot

**Comment by gignat88** [comment]
found : in site have floorplan tab for my site :) noob

**Comment by mcmag777** [comment]
Hi! Is there no ready-made solution with installation on netbox 4.1.X?

**Comment by litebito** [comment]
See here: https://github.com/netbox-community/netbox-floorplan-plugin/issues/43
