### ISSUE TITLE
ImportError when running makemigrations

### ISSUE THREAD

**Issue by vmorris** [netbox-community/netbox-floorplan-plugin#56]
I'm getting this error when attempting to makemigrations for netbox-floorplan-plugin on a clean install of Netbox.

- Netbox version 4.0.11
- netbox-floorplan-plugin==0.4.1

```
Making migrations for netbox_floorplan_plugin ...
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/opt/netbox/venv/lib64/python3.13/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "/opt/netbox/venv/lib64/python3.13/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
    ~~~~~~~~~~~~^^
  File "/opt/netbox/venv/lib64/python3.13/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib64/python3.13/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/opt/netbox/venv/lib64/python3.13/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
    ~~~~~~~~~~~~~^^^^^^^
  File "/usr/lib64/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/netbox/venv/lib64/python3.13/site-packages/strawberry_django/__init__.py", line 1, in <module>
    from . import auth, filters, mutations, ordering, pagination, relay
  File "/opt/netbox/venv/lib64/python3.13/site-packages/strawberry_django/auth/__init__.py", line 1, in <module>
    from .mutations import login, logout, register
  File "/opt/netbox/venv/lib64/python3.13/site-packages/strawberry_django/auth/mutations.py", line 6, in <module>
    import strawberry
  File "/opt/netbox/venv/lib64/python3.13/site-packages/strawberry/__init__.py", line 7, in <module>
    from . import experimental, federation, relay
  File "/opt/netbox/venv/lib64/python3.13/site-packages/strawberry/federation/__init__.py", line 5, in <module>
    from .object_type import input, interface, interface_object, type
  File "/opt/netbox/venv/lib64/python3.13/site-packages/strawberry/federation/object_type.py", line 17, in <module>
    from strawberry.types.object_type import type as base_type
  File "/opt/netbox/venv/lib64/python3.13/site-packages/strawberry/types/object_type.py", line 25, in <module>
    from strawberry.utils.dataclasses import add_custom_init_fn
  File "/opt/netbox/venv/lib64/python3.13/site-packages/strawberry/utils/dataclasses.py", line 13, in <module>
    from strawberry.ext.dataclasses.dataclasses import dataclass_init_fn
  File "/opt/netbox/venv/lib64/python3.13/site-packages/strawberry/ext/dataclasses/dataclasses.py", line 5, in <module>
    from dataclasses import (  # type: ignore
    ...<7 lines>...
    )
ImportError: cannot import name '_create_fn' from 'dataclasses' (/usr/lib64/python3.13/dataclasses.py)
Error: building at STEP "RUN /opt/netbox/initialize.sh": while running runtime: exit status 1
```

**Comment by cruse1977** [comment]
hi @vmorris - I think we need more detail here - just tried 0.4.1 on a fresh install of NetBox v4.0.11 in docker and didn't see this error.

**Comment by vmorris** [comment]
Hi, I've moved on from this need for now.. I may try again to install this plugin in the future but I will not be able to reproduce any additional information. If it's working for you then I think we can close this issue.
