### ISSUE TITLE
v0.5.0 version does not work: various occurrences of "ReferenceError" in dev console

### ISSUE THREAD

**Issue by litebito** [netbox-community/netbox-floorplan-plugin#63]
Hi,

I'm running:
- Netbox 4.1.7
- netbox-floorplan-plugin 0.5.0

No errors during installation, but the plugin does not work.
In a location, I can go to the tab "Floorplan" but when I click on "edit floorplan" 
I get the following in the netbox_debug log:

```
Exception while resolving variable 'name' in template 'netbox_floorplan/floorplan_edit.html'.
Traceback (most recent call last):
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/template/base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'Floorplan' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Floorplan' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/template/base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <Floorplan: BTB01 Floorplan>
Exception while resolving variable 'id' in template 'netbox_floorplan/floorplan_edit.html'.
Traceback (most recent call last):
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/template/base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/template/base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [id] in None
```

It continues in edit mode, but if I then try to click buttons like "Set Dimensions" or "Set/Edit Background" 
nothing happens in de netbox_debug log, but in the browser dev console, I see following errors:

```
Uncaught ReferenceError: fabric is not defined
    at view.js:12:14
edit.js:26  Uncaught ReferenceError: htmx is not defined
    at edit.js:26:1
edit/:1  Uncaught ReferenceError: set_dimensions is not defined
    at HTMLAnchorElement.onclick (edit/:1:1)
edit/:1  Uncaught ReferenceError: set_background is not defined
    at HTMLAnchorElement.onclick (edit/:1:1)
```

I already tried to:
1/ check if the files are there: yes:

```
# ls -l /opt/netbox/netbox/static/netbox_floorplan/floorplan/
total 44
-rw-r--r--. 1 root root 26287 Dec  9 15:03 edit.js
-rw-r--r--. 1 root root  8390 Dec  9 15:03 utils.js
-rw-r--r--. 1 root root  1515 Dec  9 15:03 view.js
# ls -l /opt/netbox/netbox/static/netbox_floorplan/vendors/
total 444
-rw-r--r--. 1 root root 312284 Dec  9 15:03 fabric-js-6.0.2.js
-rw-r--r--. 1 root root  48101 Dec  9 15:03 htmx.min.js
-rw-r--r--. 1 root root  87533 Dec  9 15:03 jquery-3.7.1.js
```
2/ redo the migrations & collect static
(no errors)

How can we fix this?

**Comment by cruse1977** [comment]
Hi,  I've not seen this error in development, however I can look at this - however you haven't included much information and 2/ confuses this.

- new install or upgrade
- are you stating you need to run collectstatic twice and this resolves this ?
-

**Comment by litebito** [comment]
Hi,

to answer your questions:
- it is about adding the floorplanplugin to an existing Netbox installation
- no, I ran collect static, and I ran migrations, as this fixed a similar issue in other posts here, but that did not fix the issue
- netbox is using the default basepath
- I'll check on the loadingstatus and webserverlogs of the javascript as soon as I'm back in the office tomorrow

**Comment by cruse1977** [comment]
Hi,  still unable to reproduce this - was a previous version of floorplan installed at some point and also is this standard install, docker etc ?

**Comment by litebito** [comment]
Hi, 
this is a standard (no docker) install.
I upgraded floorplan from 0.4.1 to 0.5.0

**Comment by HiImVINK** [comment]
I think im having the same issue. (but a different kind of deployment) 
It seems like the vendor scripts are not loaded correctly

![Image](https://github.com/user-attachments/assets/1e1846d6-4bfe-4718-97f4-91e79a3fb039)

![Image](https://github.com/user-attachments/assets/cc69ae81-f34a-4016-9492-068abdc33b2b)

i have built the docker image like this:

`
# Use the official NetBox image as the base
FROM ghcr.io/netbox-community/netbox:v4.2.3

# Copy plugin requirements to netbox
COPY ./plugin_requirements.txt /opt/netbox/
# Install using pip install
RUN /usr/local/bin/uv pip install -r /opt/netbox/plugin_requirements.txt

# These lines are only required if your plugin has its own static files.
COPY ./configuration/configuration.py /etc/netbox/config/configuration.py
COPY ./configuration/plugins.py /etc/netbox/config/plugins.py
RUN DEBUG="true" SECRET_KEY="dummydummydummydummydummydummydummydummydummydummy" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input
`

I then make it available using the helm chart:

`
image:
  registry: registry.domain.com
  repository: library/netbox-custom
  pullPolicy: Always

global:
  storageClass: "longhorn-replicated"

persistence:
  enabled: true
  storageClass: "longhorn-replicated"

postgresql:
  enabled: true
  auth:
    username: netbox
    database: netbox

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: netbox
            app.kubernetes.io/name: netbox
            app.kubernetes.io/component: netbox
        topologyKey: kubernetes.io/hostname

ingress:
  enabled: true
  pathType: ImplementationSpecific
  className: ""
  annotations:
      kubernetes.io/ingress.class: traefik-external
      cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: netbox.domain.com
      paths:
        - /
  tls: 
    - secretName: netbox-ssl
      hosts:
        - netbox.vink-it.com



# Enable installed plugins. Add the name of each plugin to the list. , 'netbox_diode_plugin'
plugins:
  - netbox_dns
  - netbox_floorplan
  - netbox_qrcode

# Plugins configuration settings. These settings are used by various plugins
# that the user may have installed. Each key in the dictionary is the name of
# an installed plugin and its value is a dictionary of settings.
pluginsConfig:
  netbox_dns: {}
  netbox_floorplan: {}
  netbox_qrcode: {}
`

**Comment by cruse1977** [comment]
@HiImVINK  I'd be interested to know what happens if you connect to your container and run collectstatic manually.
